### PR TITLE
 Migrate to a Web Extension #101 

### PR DESCRIPTION
**Pull request by Hrushi20**
Hey!

### Current Progress-
I added the main entry file in the browser property in package.json file
Used webpack as node.js modules are not supported in vs code web extension.
The extension is being detected in the vscode browser and is able to identify the required files. 
The extension is also downloadable in the browser.

### Difficulties facing-
 Not able to connect server with the web extension. Server functionalities are not being displayed in the browser.
Also I am not sure about the resolve.fallback is webpack.config.js. For now i just downloaded the dependencies. I can remove the unwanted dependencies. Not sure what to include and what to exclude.

### Related Issues-
- Issue #101 

Thank You

### CODE REVIEW

**Comment by Hrushi20** [comment]
Hey! 
I adding the webpack configuration for server folder.

I am getting this error while starting the web extension in debugger mode.
`STOPPED on first line for debugging on port 53357`

I am getting this error while starting the web extension in my local Vscode.

Extension Startup error

Can you help me out in fixing this issue.

Thank you.

**Comment by Hrushi20** [comment]
Hey!
I am not able to find any stack error. The variable process is not defined in the vscode sandbox. I am not sure if it is a webpack issue. Can you guide me to solve this issue.
Thank You.

**Comment by Hrushi20** [comment]
Screenshot from 2022-02-05 14-00-08

The issue is related to Buffer() being deprecated. Vscode doesn't allows Buffer() to be used anymore.

**Comment by dselman** [comment]
> I get this error when the extension is being activated in vscode. The issue is due the this import in the commandHandler.ts
> 
> `const Engine = require('@accordproject/cicero-engine').Engine;`
> 
> I get the following error when I uncomment the above code.
> 
> Screenshot from 2022-02-05 19-15-06
> 
> If I comment the above code, the extension is working as expected. I added a console.log() when clicking export cicero archive
> 
> Screenshot from 2022-02-05 19-18-40
> 
> I don't know what is the issue with this dependency ` @accordproject/cicero-engine`
> 
> Also I get this error while building webpack and I feel due to this the cicero-engine is causing a problem. I am not sure how to fix this issue. The vm2 module is not being browserified.
> 
> > WARNING in ./client/node_modules/vm2/lib/main.js 20:11-43
> > Module not found: Error: Can't resolve 'coffee-script' in '/home/hrushi/Programming/OpenSource/accordProject/cicero-vscode-extension/client/node_modules/vm2/lib'
> > @ ./client/node_modules/vm2/index.js 3:0-38
> > @ ./client/node_modules/@accordproject/ergo-engine/lib/vmengine.js 33:4-18
> > @ ./client/node_modules/@accordproject/ergo-engine/index.js 23:0-54
> > @ ./client/node_modules/@accordproject/cicero-engine/lib/engine.js 17:19-65
> > @ ./client/node_modules/@accordproject/cicero-engine/index.js 22:0-50
> > @ ./client/src/commandHandlers.ts 30:15-61
> > @ ./client/src/extension.ts 18:26-54
> 
> > WARNING in ./client/node_modules/vm2/lib/main.js 151:26-33
> > Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
> > @ ./client/node_modules/vm2/index.js 3:0-38
> > @ ./client/node_modules/@accordproject/ergo-engine/lib/vmengine.js 33:4-18
> > @ ./client/node_modules/@accordproject/ergo-engine/index.js 23:0-54
> > @ ./client/node_modules/@accordproject/cicero-engine/lib/engine.js 17:19-65
> > @ ./client/node_modules/@accordproject/cicero-engine/index.js 22:0-50
> > @ ./client/src/commandHandlers.ts 30:15-61
> > @ ./client/src/extension.ts 18:26-54
> 
> This is the package I used in webpack for browserifiying vm2 https://www.npmjs.com/package/vm-browserify
> 
> Thank You

That's good progress, I think. One approach would be to remove the Engine dependency and to lose those features from the extension so we can unblock this. Can you try that please?

**Comment by Hrushi20** [comment]
Sure. I'll try that out. 
Thank you.

**Comment by dselman** [comment]
Superseded by https://github.com/accordproject/cicero-vscode-extension/pull/128

**Pull request closed without merging**
